//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MusicStarterBackend
{
    using System;
    using System.Collections.Generic;
    
    public partial class Track
    {
        public int Id { get; set; }
        public string Title { get; set; }
        public System.TimeSpan Duration { get; set; }
        public System.DateTime DateTime { get; set; }
        public double Rating { get; set; }
        public string File { get; set; }
    
        public virtual Author Author { get; set; }
        public virtual Album Album { get; set; }
    }
}
